-- Run this schema script in your Supabase SQL Editor
-- This will build out the infrastructure matching the admin backend

-- 1. Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    category text not null,
    tech jsonb not null default '[]'::jsonb,
    icon text,
    customIcon text,
    featured boolean default false,
    coverImage boolean default false,
    covers jsonb,
    link text not null,
    previewUrl text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint generated by default as identity primary key,
    client_name text not null,
    client_role text not null,
    project_reference text,
    review text not null,
    rating int not null default 5,
    avatar_fallback text not null,
    is_published boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Inquiries Table
CREATE TABLE IF NOT EXISTS public.inquiries (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    email text not null,
    project_type text not null,
    message text not null,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    id int primary key default 1,
    site_title text not null default 'Devesters',
    site_description text,
    contact_email text,
    contact_phone text,
    github_url text,
    linkedin_url text,
    twitter_url text,
    hero_title text,
    hero_subtitle text,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    CONSTRAINT single_row CHECK (id = 1)
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 6. Create Security Policies
-- Anyone can read projects & published testimonials
CREATE POLICY "Public read access on projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Public read access on testimonials" ON public.testimonials FOR SELECT USING (is_published = true);

-- Anyone can insert inquiries
CREATE POLICY "Public insert access on inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);

-- Authenticated admins can do everything
CREATE POLICY "Admin full access on projects" ON public.projects FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on testimonials" ON public.testimonials FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on inquiries" ON public.inquiries FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin full access on settings" ON public.settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Public read access on settings" ON public.settings FOR SELECT USING (true);
